#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn clean install
#      - name: Log in to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build Docker image
#        run: docker build -t aliaskar2003/chat .
#      - name: Publish image to docker hub
#        run: docker push aliaskar2003/chat:latest
#
#  deploy:
#    needs: build
#    runs-on: 'self-hosted'
#    steps:
#      - name: Pull image Docker Hub
#        run: docker pull aliaskar2003/chat:latest
#      - name: Run docker container
#        run: docker run -d -p 8081:8081 --name chat-container aliaskar2003/chat:latest
